### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by barncastle** [wowdev/TACT.Net#1]
- [x] Double check cross platform compatibility for the ZLib implementation - *windows & linux*
- [x] Confirm SystemFile versioning
- [x] Verify if `archive-group` is required and if so, the format - *it is still optional, will implement if this changes*
- [x] Add `file-index-size` and `archives-index-size` (what is this?) - *size of index file works but isn't right*
- [ ] Implement Index checksums (how is this calculated?)
- [ ] Patch write support (is this even needed?)
- [x] Use CDNConfig `Path` variable to support non-`tpr/wow` directory structures (refactored so this isn't necessary, TACTRepo should now point to the root folder)
- [ ] Add Ribbit server support (optional).

**Comment by MaxtorCoder** [comment]
Looking to `archive-group`, it is required since 8.2.
